### ISSUE TITLE
Question for Spline Curves

### ISSUE THREAD

**Issue by SCUTykLin** [buaavrcg/Neural3DStrokes#3]
Why do we use spline curves to represent stroke? Some simpler shapes, such as Sphere, wouldn't it be better to use their origin and radius directly? like gaussian splatting. And when u calculate the sdf, u can directly find the stroke which interact with the query points

Thanks.

**Comment by dhbloo** [comment]
Hi, 

We do have simpler shapes including spheres and ellipsoids, which are in the primitive strokes category. For these simple primitives, we use the analytical formula of their SDFs. 


> And when u calculate the sdf, u can directly find the stroke which interact with the query points

Do you mean applying the ray-SDF intersection test instead of ray marching of the SDF volume? Indeed this can lead to a faster finding of intersection points for simple SDFs, however for more complex shapes, there may not exist an analytical formula to compute the intersection point, and some kind of root finding scheme is required, which is not computationally cheaper than the current method. In addition, using ray tracing will lead to a surface-based rendering model, which can be more difficult to optimize than the volume-based rendering model in this method. Considering these points, we end up using ray marching, which also allows it to be adapted to arbitrary shapes of strokes.

**Comment by SCUTykLin** [comment]
Thanks for your reply

**Comment by SCUTykLin** [comment]
hello, I find that u calculate sdf value twice in strokes_forward.cu. 
`    float sdf_value = BaseSDF<sdf_type>::sdf(pos, shape_params);
    if (sdf_output)
        sdf_output[idx_thread] = sdf_value;

    // scale radii if singlescale or multiscale is enabled
    if (inv_scale_radius) {
        if constexpr (enable_singlescale) {
            float scale = sp_reverse[0];
            radii /= scale;
        } else if constexpr (enable_multiscale) {
            // For multiscale transform, we need to find the direction of sdf gradient
            // and compute the scale factor from this gradient direction
            float3 sdf_grad = BaseSDF<sdf_type>::grad_sdf(nullptr, 0.0f, pos, shape_params);
            // Compute the scale factor from the gradient direction
            float3 scale = *(const float3 *)(sp_reverse);
            float3 sdf_grad_scaled = sdf_grad * scale;
            radii /= (length(sdf_grad_scaled) / length(sdf_grad));
        }
    }`

can u tell me why? thanks

**Comment by SCUTykLin** [comment]
Page 4, "we use a general approximation method to compute the SDF: we uniformly sample K + 1 positions on the curve to get K line segments, and calculate the distance from these segments to the query point respectively, thereby obtaining an approximate nearest point. "  Can u point out where in the code it is?

Thanks

**Comment by dhbloo** [comment]
> hello, I find that u calculate sdf value twice in strokes_forward.cu. ` float sdf_value = BaseSDF<sdf_type>::sdf(pos, shape_params); if (sdf_output) sdf_output[idx_thread] = sdf_value;
> 
> ```
> // scale radii if singlescale or multiscale is enabled
> if (inv_scale_radius) {
>     if constexpr (enable_singlescale) {
>         float scale = sp_reverse[0];
>         radii /= scale;
>     } else if constexpr (enable_multiscale) {
>         // For multiscale transform, we need to find the direction of sdf gradient
>         // and compute the scale factor from this gradient direction
>         float3 sdf_grad = BaseSDF<sdf_type>::grad_sdf(nullptr, 0.0f, pos, shape_params);
>         // Compute the scale factor from the gradient direction
>         float3 scale = *(const float3 *)(sp_reverse);
>         float3 sdf_grad_scaled = sdf_grad * scale;
>         radii /= (length(sdf_grad_scaled) / length(sdf_grad));
>     }
> }`
> ```
> 
> can u tell me why? thanks

Hi,

It does not compute the SDF value twice, but computes the SDF gradient if the adaptive scaling is enabled (`inv_scale_radius=true` and `enable_multiscale=true`). We use the gradient of SDF function (a unit vector representing the normal direction) and multi-scale vector to estimate how much the SDF is stretched, and modify the radii used to compute the alpha value.

**Comment by dhbloo** [comment]
> Page 4, "we use a general approximation method to compute the SDF: we uniformly sample K + 1 positions on the curve to get K line segments, and calculate the distance from these segments to the query point respectively, thereby obtaining an approximate nearest point. " Can u point out where in the code it is?
> 
> Thanks

Please refer to https://github.com/buaavrcg/Neural3DStrokes/blob/6d8d6766d396d7a17492f45412819e8770d15a56/source/strokelib/src/strokes_sdf.h#L1253-L1276

**Comment by SCUTykLin** [comment]
Thanks very much!
